version: '3.8'

services:
  bot:
    build: .
    container_name: poker_bot
    env_file:
      - .env
    volumes:
      - ./poker.db:/app/poker.db  # для хранения базы данных вне контейнера
    restart: unless-stopped
